site_name: OpenBoxes
site_description: 
site_author: Justin Miranda
theme: readthedocs
repo_url: https://github.com/openboxes/openboxes
include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2017, OpenBoxes
google_analytics: ['UA-37396941-2', 'OpenBoxes']

pages:

# About:
- ['index.md', 'About', 'Introduction']
- ['benefits.md', 'About', 'Benefits']
- ['considerations.md', 'About', 'Considerations']

# Deployment
- ['installation/index.md', 'Deployment Guide',  'Installation']
- ['installation/ubuntu.md', 'Deployment Guide', 'Install on Ubuntu 14.04']
- ['installation/macos.md', 'Deployment Guide', 'Install on Mac OS']
- ['installation/windows.md', 'Deployment Guide', 'Install on Windows']

# Upgrade
- ['upgrading/index.md', 'Deployment Guide', 'Upgrading']

# Configuration
- ['configuration/configuration.md', 'Configuration Guide', 'General']
- ['configuration/database.md', 'Configuration Guide', 'Database']
- ['configuration/email.md', 'Configuration Guide', 'Email']
- ['configuration/application.md', 'Configuration Guide', 'Application']
- ['configuration/example.md', 'Configuration Guide', 'Example']

# Developer Guide
- ['developer-guide/index.md', 'Developer Guide', 'Introduction']
- ['developer-guide/getting-started.md', 'Developer Guide', 'Getting Started']
- ['developer-guide/contributing.md', 'Developer Guide', 'Contributing']
- ['developer-guide/syncing-a-fork.md', 'Developer Guide', 'Syncing a Fork']
- ['developer-guide/tagging.md', 'Developer Guide', 'Tagging a Release']

# Support - add a page like https://readthedocs.org/support/
- ['support/index.md', 'Support', 'Introduction']

# User Guide
- ['user-guide/index.md', 'User Guide', 'Introduction']

# Continuous Integration
# User Guide
# HowTo
# Cloud

# Releases:
- ['release-notes.md', 'Releases', 'Release Notes']


